### ISSUE TITLE
1.31 bug

### ISSUE THREAD

**Issue by ghost** [ZorbZorbZorb/ZorbsStartConditionModifier#2]
![QQ截图20210218105902](https://user-images.githubusercontent.com/55522934/108299431-63bb6700-71d9-11eb-8622-65f4bf458221.png)
![QQ截图20210218110658](https://user-images.githubusercontent.com/55522934/108299476-7766cd80-71d9-11eb-9778-75adf0236c41.png)
![QQ截图20210218110708](https://user-images.githubusercontent.com/55522934/108299488-7a61be00-71d9-11eb-99a4-df3ec361ffe7.png)

**Comment by ZorbZorbZorb** [comment]
Corrected in commit https://github.com/ZorbZorbZorb/ZorbsStartConditionModifier/commit/cd655a49415ab41aca0b0cf039362fda10a4ae80
